var seform = require('seform'),
    seformForm = seform.Form;

var Form = function() {
  return this.init.apply(this, arguments);
};

Form.prototype = new seformForm();
Form.prototype.constructor = Form;

Form.prototype.init = function(instance) {
  var fields = [],
      buttons = [];

  return seformForm.prototype.init.apply(this, [fields, buttons, {}]);
};

Form.prototype.filter = function(field) {
  return !!field._autoGenerated;
};

Form.prototype.mapping = function(fieldType) {
  switch(fieldType) {
    case 'BOOLEAN':
      return 'CheckboxChoice';
      break;
    case 'ENUM':
    case 'ARRAY':
      return 'RadioChoice';
      break;
    case 'TEXT':
      return 'Textarea';
      break;
    default:
      return 'Input';
  }
};

module.exports = Form;